apiVersion: v1
kind: PresistentVolumeClaim
metadata: 
	name:pvc-webserver
spec:
	accessModes:
		- ReadWriteOnce
	resources:
		requests:
			storage: 3Gi
			
------
kind: Pod
apiVersion: v1
metadata: 
	name: pod-nginx
spec: 
	volumes:
		- name: server-storage
			persistentVolumeClaim:
					claimName: pvc-webserver
	containers:
		- name: pv-container
			image: nginx
			ports:
				- containerPort: 80
					name: webserver
			volumeMounts:
				- mountPath: "/usr/share/nginx/html"
					name: server-storage
