apiVersion: v1
kind: Pod
metadata: 
  name: webserver
  labels: 
    env : production
    owner : don
    webserver : nginx
    country : EG
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports: 
      - containerPort: 80